name: tdb_closet
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  shared_preferences: ^2.5.3
  firebase_auth: ^6.1.2
  fluttertoast: ^9.0.0
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Fonts
  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300